# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.
import itertools

report: "report/workflow.rst"
include: "rules/common.smk"
localrules: ftp_first, ftp_second

# Allow users to fix the underlying OS via singularity.
rule all:
    input:
        #expand("../data/reads/{file_f}", file_f=list(itertools.chain.from_iterable(samples2.loc[samples2["sample"], ["f_fq1", "f_fq2"]].values))),
        #expand("../data/reads/{file_s}", file_s=list(itertools.chain.from_iterable(samples2.loc[samples2["sample"], ["s_fq1", "s_fq2"]].values))),
        expand("../data/spades_assemblies/{sample}/scaffolds.fa", sample=samples["sample"]),
        "../data/concat_trimmed/multiqc_report.html"

        # The first rule should define the default target files
        # Subsequent target rules can be specified below. They should start with all_*.

include: "rules/trim.smk"
include: "rules/concat_reads.smk"
include: "rules/assemble.smk"
include: "rules/other.smk"
include: "rules/fastqc_analysis.smk"
