# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.


report: "report/workflow.rst"

# Allow users to fix the underlying OS via singularity.

rule all:
    input:
        "../results/plots/Contig_Length_Distribution.png"
        # The first rule should define the default target files
        # Subsequent target rules can be specified below. They should start with all_*.


include: "rules/common.smk"
include: "rules/trim.smk"
include: "rules/merge_reads.smk"
include: "rules/assemble.smk"
include: "rules/other.smk"
